### ISSUE TITLE
Request - delete image from input after processing

### ISSUE THREAD

**Issue by jasonmadigan** [danecreekphotography/node-deepstackai-trigger#285]
**Is your feature request related to a problem? Please describe.**
I've noticed some bad slowdown (20s+) in processing when my aiinput folder grows large (~1000 files). To combat, I've adjusted BlueIris to purge images older than an hour in the input folder, but even that can still see the input folder grow large.

**Describe the solution you'd like**
It'd be nice if there could be a trigger processing option to delete images from the input folder after processing. Obviously, the annotated images could remain for push notifications etc., but they're stored on a different volume anyway.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by danecreekphotography** [comment]
I've toyed with doing this but don't think the tool should be in the business of managing the purging of images it didn't create. It does auto-purge annotated images, but that's because it made them.

I suggest doing exactly what you've done (which is how I run): since BlueIris created the images, BlueIris can delete the images. Mine is set to 1GB/1 hr retention.
