### ISSUE TITLE
cooldownTimer for Telegram triggers

### ISSUE THREAD

**Issue by Viksie** [danecreekphotography/node-deepstackai-trigger#297]
With webRequests a single image is provided for analyses on motion detection. Upon object identification, the object isn't always within the snapshot being presented via Telegram. By adjusting the sensitivity of the particular VMS's motion detection, additional images can be presented to the user if the "cooldownTimer for Telegram" #87 could be adjusted manually from the current 60 seconds.

Could "cooldownTime" for Telegram be plumbed through to be set within settings.json ?

Thanks

**Comment by danecreekphotography** [comment]
Individual `cooldownTime` is already supported for every trigger, and can even be overridden independently on the Telegram handler as well. The default is always 0, if you are seeing something other than that it's because your trigger.json file is specifying something else.

https://github.com/danecreekphotography/node-deepstackai-trigger/wiki/Defining-triggers

https://github.com/danecreekphotography/node-deepstackai-trigger/wiki/Defining-triggers#defining-telegram-handlers
